server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 4YBhTtRy6ZUug9yesCYn
    url: jdbc:mysql://updxcu6y4xaecqac:4YBhTtRy6ZUug9yesCYn@bxqlctthoz98osljpsts-mysql.services.clever-cloud.com:3306/bxqlctthoz98osljpsts
    username: updxcu6y4xaecqac
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: qk.khai2712@gmail.com
    password: pqvyciabeldoifwg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 3777217A25432A462D4A614E645267556B58703273357538782F413F4428472B
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  business:
    base-salary: 1490000
    personal-deductions: 11000000